environment:
  home: C:\projects

version: '{branch}-{build}'

os: Visual Studio 2015

before_build:
  - cmd: 'cmake --version'
  - cmd: cd %home%\tinyosc-sfl\test
  # creating the CMakeLists.txt so that cmake can create the Visual Studio project (.sln)
  - cmd: echo project (test-bin) >> CMakeLists.txt
  - cmd: echo include_directories(..) >> CMakeLists.txt
  - cmd: echo add_executable(test-bin test.c) >> CMakeLists.txt
  # generating the Visual Studio .sln project with cmake
  - cmd: cmake .

build:
  project: C:\projects\tinyosc-sfl\test\test-bin.sln

after_build:
  - cmd: C:\projects\tinyosc-sfl\test\Release\test-bin.exe

configuration:
  - Release
